move_speed = 3;
aim_dir = 0;
facing_x = 0;
facing_y = 1;
mine_target = noone;
mine_timer = 0;
mine_duration = 60;
image_xscale = 0.026;
image_yscale = 0.026;
depth = -9999;  // player + pickaxe render above all room objects
